name: 24h-Product-Machine
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-machine:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests fpdf2

      - name: Create Product
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python machine.py

      - name: Commit and Push
        run: |
          git config --global user.name "MachineBot"
          git config --global user.email "bot@github.com"
          git add products/ # Adiciona a pasta inteira, evita erro de wildcard
          # Só faz o commit se houver arquivos novos para evitar erro 128
          git diff --quiet && git diff --staged --quiet || (git commit -m "New product generated" && git push)
